# This is a basic workflow to help you get started with Actions

name: BuildTestCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  # pull_request:
  #   branches: [ "develop" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ windows-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Adding microsoft setup build
      - name: Setup Ms Build
        uses: microsoft/setup-msbuild@v1.3.1
        
      # Adding NuGet setup build
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.1.1
        
      # Create a Build directory
      - name: Create Build Directory
        run: mkdir _build

      - name: Restore Nuget Package
        run: nuget restore Code/WolfordV2/WolfordApis.sln
      
      - name: Build the solution
        run: msbuild Code/WolfordV2/WolfordApis.sln /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: WolfordApis
          path: "./_build"        
      
  release:
    needs: build
    runs-on: [ windows-latest ]
    steps:
      - name: Download Artifact from build
        uses: actions/download-artifact@v3
        with:
          name: WolfordApis
          path: "./_build"      
          
          
          
          
          
