name: Deploy to Azure Web App

on:
  push:
    branches:
      - feature/new-build

env:
  AZURE_WEBAPP_NAME: <your-web-app-name>
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}/MyWebApp.zip
  PATH_SOLUTION: Code/WolfordV2/WolfordApis.sln

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe path
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore Nuget Package
      run: nuget restore ${{ env.PATH_SOLUTION }}

    - name: Build the solution
      run: msbuild ${{ env.PATH_SOLUTION }} /p:Configuration=Release

    # - name: Publish to Azure Web App
    #   uses: Azure/webapps-deploy@v2
    #   with:
    #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
