name: Deploy to Azure Web App

on:
  push:
    branches:
      - feature/new-build

env:
  AZURE_WEBAPP_NAME: <your-web-app-name>
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}/MyWebApp.zip
  PATH_SOLUTION: Code/WolfordV2/WolfordApis.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe path
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore Nuget Package
      run: nuget restore ${{ env.PATH_SOLUTION }}

    - name: Build the solution
      run: msbuild ${{ env.PATH_SOLUTION }} /p:Configuration=Release
      
    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: WolfordApis/bin/Release
        
  # deploy:
  #   needs: build
  #   runs-on: windows-latest
  #
  #   steps:
  #   - name: Download build artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: build-artifact
  #       path: build-artifact
  #       
  #   - name: Set MyVariable value
  #     run: echo "Hello, world!" > MyVariable



