name: Deploy to Azure Web App

on:
  push:
    branches: [ "develop" ]

env:
  AZURE_WEBAPP_NAME: <your-web-app-name>
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}/MyWebApp.zip
  PATH_SOLUTION: Code/WolfordV2/WolfordApis.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history

    - name: Setup MSBuild.exe path
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore Nuget Package
      run: nuget restore ${{ env.PATH_SOLUTION }}

    - name: Build the solution
      run: msbuild ${{ env.PATH_SOLUTION }} /p:Configuration=Release
      
    - name: Determine version number
      id: version
      uses: SemVer-Next/semver-next@v1.1.1
      with:
        tagPrefix: v
        prereleasePrefix: pre
      
    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: Code/WolfordV2/WolfordApis-${{ steps.version.outputs.version }}
        
  deploy:
    needs: build
    runs-on: windows-latest
  
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        
    - name: Set MyVariable value
      run: echo "Hello, world!" > MyVariable

