name: Deploy to Azure Web App

on:
  push:
    branches:
      - develop

env:
  # AZURE_WEBAPP_NAME: "your-web-app-name"
  AZURE_WEBAPP_PACKAGE_PATH: "./webapp.zip"
  AZURE_WEBAPP_SLOT_NAME: "your-slot-name"
  AZURE_WEBAPP_SUBSCRIPTION_ID: "your-subscription-id"
  AZURE_WEBAPP_RESOURCE_GROUP: "your-resource-group-name"
  AZURE_WEBAPP_APP_SERVICE_PLAN_NAME: "your-app-service-plan-name"
  DOTNET_VERSION: "4.8"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Framework ${{ env.DOTNET_VERSION }}
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Build and publish .NET Framework web app
      run: |
        dotnet restore
        dotnet publish -c Release -o "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

    # - name: Deploy to Azure Web App
    #   uses: Azure/webapps-deploy@v2
    #   with:
    #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #     slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    #     subscription-id: ${{ env.AZURE_WEBAPP_SUBSCRIPTION_ID }}
    #     resource-group: ${{ env.AZURE_WEBAPP_RESOURCE_GROUP }}
    #     app-service-plan: ${{ env.AZURE_WEBAPP_APP_SERVICE_PLAN_NAME }}
